#!/usr/bin/env bash
# Andes Chatbot — one-click install (Docker + automatic HTTPS via Caddy)
# Usage: chmod +x install.sh && ./install.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${BLUE}→${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
fail()  { echo -e "${RED}✗${NC} $*"; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing: $1"
}

prompt() {
  local var_name="$1"
  local question="$2"
  local default="${3:-}"
  local value=""
  if [[ -n "$default" ]]; then
    read -r -p "$question [$default]: " value
    value="${value:-$default}"
  else
    read -r -p "$question: " value
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"
  local question="$2"
  local value=""
  read -r -s -p "$question: " value
  echo ""
  printf -v "$var_name" '%s' "$value"
}

normalize_url() {
  local u="$1"
  u="${u%/}"
  echo "$u"
}

domain_from_url() {
  local u="$1"
  u="${u#https://}"
  u="${u#http://}"
  echo "${u%%/*}"
}

banner() {
  cat <<'EOF'

  ============================================================
    ANDES CHATBOT — ONE-CLICK INSTALL
  ============================================================

    Starts:
      • Chatbot API (Docker)
      • Caddy reverse proxy (automatic HTTPS — no certbot)

    You need:
      • Docker installed
      • DNS pointing your domain to this server
      • Ports 80 and 443 open on the firewall

    WordPress: install the plugin from wordpress-plugin/andes-ai-chatbot/

EOF
}

check_prereqs() {
  info "Checking Docker..."
  require_cmd docker
  docker compose version >/dev/null 2>&1 || fail "Need Docker Compose v2 (docker compose)"
  ok "Docker ready"
}

collect_config() {
  echo ""
  prompt API_PUBLIC_URL "Chatbot domain (https://)" "https://chatbot-staging.andestech.com"
  API_PUBLIC_URL="$(normalize_url "$API_PUBLIC_URL")"
  [[ "$API_PUBLIC_URL" =~ ^https:// ]] || fail "URL must start with https://"

  CHATBOT_DOMAIN="$(domain_from_url "$API_PUBLIC_URL")"
  [[ -n "$CHATBOT_DOMAIN" ]] || fail "Could not parse domain from URL"

  prompt WP_SITE_URL "WordPress site URL" "https://www.andestech.com"
  WP_SITE_URL="$(normalize_url "$WP_SITE_URL")"

  ALLOWED_ORIGINS="$WP_SITE_URL"
  read -r -p "Also allow www.andestech.com? [Y/n]: " extra_www
  extra_www="${extra_www:-Y}"
  if [[ "$extra_www" =~ ^[Yy] ]]; then
    ALLOWED_ORIGINS="${ALLOWED_ORIGINS},https://www.andestech.com,https://andestech.com"
  fi

  if [[ -f .env ]] && grep -q GOOGLE_API_KEY .env 2>/dev/null; then
    read -r -p "Reuse GOOGLE_API_KEY from existing .env? [Y/n]: " reuse
    reuse="${reuse:-Y}"
    if [[ "$reuse" =~ ^[Yy] ]]; then
      # shellcheck disable=SC1091
      source .env
      GOOGLE_API_KEY="${GOOGLE_API_KEY:-}"
      CRON_SECRET="${CRON_SECRET:-}"
    fi
  fi

  if [[ -z "${GOOGLE_API_KEY:-}" ]]; then
    prompt_secret GOOGLE_API_KEY "GOOGLE_API_KEY"
    [[ -n "$GOOGLE_API_KEY" ]] || fail "GOOGLE_API_KEY is required"
  fi

  if [[ -z "${CRON_SECRET:-}" ]]; then
    CRON_SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 64)"
    ok "Generated CRON_SECRET"
  fi
}

write_env() {
  info "Writing .env ..."
  cat >.env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
PORT=8000
PUBLIC_API_URL=${API_PUBLIC_URL}
CHATBOT_DOMAIN=${CHATBOT_DOMAIN}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

GOOGLE_API_KEY=${GOOGLE_API_KEY}
CRON_SECRET=${CRON_SECRET}

RAG_STORAGE=local

GEMINI_CHAT_MODEL=gemini-2.5-flash-lite
GEMINI_EMBEDDING_MODEL=gemini-embedding-001
EMBEDDING_DIMENSIONS=768

HTTP_SSL_VERIFY=true
ENABLE_DEV_ROUTES=false

CRAWL_BASE_URL=https://www.andestech.com/en/
SITEMAP_URLS=https://www.andestech.com/sitemap.xml,https://www.andestech.com/sitemap_index.xml
MAX_CRAWL_PAGES=2000
CRAWL_DELAY_SECONDS=2.5
CRAWL_CONCURRENCY=1
CRAWL_WORDFENCE_COOLDOWN=120
EOF
  chmod 600 .env
  ok "Wrote .env"
}

write_caddyfile() {
  cat >Caddyfile <<EOF
# Auto-generated by install.sh for ${CHATBOT_DOMAIN}
${CHATBOT_DOMAIN} {
	reverse_proxy api:8000
}
EOF
  ok "Wrote Caddyfile for ${CHATBOT_DOMAIN}"
}

start_stack() {
  info "Building and starting Docker (API + Caddy)..."
  docker compose -f docker-compose.full.yml up -d --build
  ok "Containers started"
}

wait_for_health() {
  info "Waiting for API..."
  local i
  for i in $(seq 1 60); do
    if docker compose -f docker-compose.full.yml exec -T api python -c \
      "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=3)" \
      >/dev/null 2>&1; then
      ok "API is healthy"
      return 0
    fi
    sleep 2
  done
  warn "API health check timed out — check: docker compose -f docker-compose.full.yml logs"
}

wait_for_https() {
  info "Waiting for HTTPS (Caddy may take 30–60s to get a certificate)..."
  local i
  for i in $(seq 1 45); do
    if curl -sf "${API_PUBLIC_URL}/health" >/dev/null 2>&1; then
      ok "HTTPS is live: ${API_PUBLIC_URL}/health"
      curl -s "${API_PUBLIC_URL}/health" | python3 -m json.tool 2>/dev/null || true
      echo ""
      return 0
    fi
    sleep 2
  done
  warn "HTTPS not ready yet. Ensure DNS points to this server and ports 80/443 are open."
  warn "Then test: curl ${API_PUBLIC_URL}/health"
}

print_done() {
  cat <<EOF

============================================================
  INSTALL COMPLETE
============================================================

  API:  ${API_PUBLIC_URL}/health
  Test: ${API_PUBLIC_URL}/test

  WORDPRESS (pick one):

  A) Plugin (recommended — no code paste):
     1. Zip folder: wordpress-plugin/andes-ai-chatbot/
     2. WP Admin -> Plugins -> Add New -> Upload
     3. Activate -> Settings -> Andes AI Chatbot
     4. API URL: ${API_PUBLIC_URL}

  B) Manual footer snippet (if you cannot install plugins):
     Settings -> Insert Headers and Footers -> Footer:

<script>
  window.ANDES_CHAT_CONFIG = {
    apiUrl: "${API_PUBLIC_URL}",
    launcherTooltip: "Chat with the Andes AI Assistant"
  };
</script>
<script src="${API_PUBLIC_URL}/widget.js"></script>

  Commands:
    Logs:   docker compose -f docker-compose.full.yml logs -f
    Stop:   docker compose -f docker-compose.full.yml down
    Start:  docker compose -f docker-compose.full.yml up -d

============================================================
EOF
}

main() {
  banner
  check_prereqs
  collect_config
  write_env
  write_caddyfile
  start_stack
  wait_for_health
  wait_for_https
  print_done
}

main "$@"
